Scripts use bash instead of sh, always install snapper, change the subvolume layout, set directory permissions on /root, don't install wget, add btrfs module to initramfs, set kernel cmdline rootflags to use subvol instead of subvolid, install btrfs-assistant, configure paccache args for paccache.timer and enable cronie service

diff --git a/scripts/chroot_user b/scripts/chroot_user
--- a/scripts/chroot_user
+++ b/scripts/chroot_user
@@ -1,33 +1,29 @@
-#!/bin/sh
+#!/bin/bash
 . "$HOME"/archix/scripts/vars
 
-cd "$HOME"
+cd "$HOME" || { printf "Failed to cd into %s" "$HOME" ; exit 1 ; }
 
 #config
 mv "$HOME"/archix/config "$HOME"/.config
 fish -c 'set -U fish_greeting'
 if [ "$ARTIX" = true ];then
-    printf "[Desktop Entry]\nExec=/usr/bin/pkill -u \"\$USER\" -x pipewire\|wireplumber ; /usr/bin/pidwait -u \"\$USER\" -x pipewire\|wireplumber ; /usr/bin/pipewire & /usr/bin/pipewire-pulse & /usr/bin/sleep 1 ; /usr/bin/wireplumber &\nName=Pipewire\nType=Application\nX-KDE-AutostartScript=true" > ~/.config/autostart/pipewire.desktop
+    printf "[Desktop Entry]\nExec=/usr/bin/pkill -u \"\$USER\" -x pipewire\|wireplumber ; /usr/bin/pidwait -u \"\$USER\" -x pipewire\|wireplumber ; /usr/bin/pipewire & /usr/bin/pipewire-pulse & /usr/bin/sleep 1 ; /usr/bin/wireplumber &\nName=Pipewire\nType=Application\nX-KDE-AutostartScript=true\n" > ~/.config/autostart/pipewire.desktop
 fi
 #Install Thumbfast
-mkdir "$HOME"/.config/mpv/scripts/
-cd "$HOME"/.config/mpv/scripts/
-#Standard OSC
-wget 'https://raw.githubusercontent.com/po5/thumbfast/5fefc9b8e995cf5e663666aa10649af799e60186/player/lua/osc.lua'
-wget 'https://raw.githubusercontent.com/po5/thumbfast/master/thumbfast.lua'
+mkdir "$HOME"/.config/mpv/scripts
+cd "$HOME"/.config/mpv/scripts || { printf "Failed to cd into %s/.config/mpv/scripts" "$HOME" ; exit 1 ; }
 
-cd "$HOME"
+#Download OSC and thumbnailer
+curl -O 'https://raw.githubusercontent.com/po5/thumbfast/5fefc9b8e995cf5e663666aa10649af799e60186/player/lua/osc.lua'
+curl -O 'https://raw.githubusercontent.com/po5/thumbfast/master/thumbfast.lua'
+
+cd "$HOME" || { printf "Failed to cd into %s" "$HOME" ; exit 1 ; }
 
 if ! [ -d "$HOME"/Games ];then
     mkdir Games
 fi
 
 flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
-
-#Make config folder
-#if ! [ -d "$HOME"/.config ];then
-#    mkdir "$HOME"/.config
-#fi
 
 #Paru
 if [ "$PABIN" = true ];then
@@ -36,9 +32,9 @@ if [ "$PABIN" = true ];then
 fi
 
 git clone https://aur.archlinux.org/"$PARU".git
-cd "$PARU"
+cd "$PARU" || { printf "Failed to cd into %s" "$PARU" ; exit 1 ; }
 makepkg -si --noconfirm
-cd "$HOME"
+cd "$HOME" || { printf "Failed to cd into %s" "$HOME" ; exit 1 ; }
 rm -rf "$PARU"
 mkdir "$HOME"/.config/paru/
 
