Switch to rate-mirrors for mirrorlist generation and verify that script is being run as root.

diff --git a/scripts/chroot b/scripts/chroot
--- a/scripts/chroot
+++ b/scripts/chroot
@@ -21,24 +21,20 @@ if [ "$ARTIX" = true ];then
 fi
 
 #Sort Mirrors
-pacman -Syu --noconfirm reflector
+pacman -Syu --noconfirm reflector rate-mirrors
+mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
 if [ "$ARTIX" = true ];then
-    sed '/http:/d' /etc/pacman.d/mirrorlist.pacnew | rankmirrors -vwn 5 - > /etc/pacman.d/mirrorlist #Rank HTTPS mirrors without modifying mirrorlist.pacnew
+    rate-mirrors --protocol https --concurrency 1 --max-mirrors-to-output 5 --disable-comments-in-file --allow-root --save /etc/pacman.d/mirrorlist artix
     mv /etc/pacman.d/mirrorlist-arch /etc/pacman.d/mirrorlist-arch.bak
-    reflector --sort rate -c "$(curl ifconfig.co/country-iso)" -p https -a 48 -f 5 --save /etc/pacman.d/mirrorlist-arch
-    if ! [ -e /etc/pacman.d/mirrorlist-arch ];then
-        mv /etc/pacman.d/mirrorlist-arch.bak /etc/pacman.d/mirrorlist-arch
-        printf "\nTHERE WAS AN ERROR WITH REFLECTOR MIRRORLIST GENERATION. PLEASE SORT MIRRORLIST MANUALLY AFTER INSTALL.\n"
-        sleep 5
-    fi
-else
-    mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
-    reflector --sort rate -c "$(curl ifconfig.co/country-iso)" -p https -a 48 -f 5 --save /etc/pacman.d/mirrorlist
-    if ! [ -e /etc/pacman.d/mirrorlist ];then
-        mv /etc/pacman.d/mirrorlist.bak /etc/pacman.d/mirrorlist
-        printf "\nTHERE WAS AN ERROR WITH REFLECTOR MIRRORLIST GENERATION. PLEASE SORT MIRRORLIST MANUALLY AFTER INSTALL.\n"
-        sleep 5
-    fi
+    rate-mirrors --protocol https --concurrency 1 --max-mirrors-to-output 5 --disable-comments-in-file --allow-root --save /etc/pacman.d/mirrorlist-arch arch
+    #sed '/http:/d' /etc/pacman.d/mirrorlist-arch.bak | sed 's/#//g' | rankmirrors -vwn 5 - > /etc/pacman.d/mirrorlist #Rank HTTPS mirrors without modifying mirrorlist.pacnew
+fi
+rate-mirrors --protocol https --concurrency 1 --max-mirrors-to-output 5 --disable-comments-in-file --allow-root --save /etc/pacman.d/mirrorlist arch
+#reflector --sort rate -c "$(curl ifconfig.co/country-iso)",* -p https -a 48 -f 5 --save /etc/pacman.d/mirrorlist
+if ! [ -e /etc/pacman.d/mirrorlist ];then
+    mv /etc/pacman.d/mirrorlist.bak /etc/pacman.d/mirrorlist
+    printf "\nTHERE WAS AN ERROR WITH MIRRORLIST GENERATION. PLEASE SORT MIRRORLIST MANUALLY AFTER INSTALL.\n"
+    sleep 5
 fi
 
 #Update to get repos
